# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f77bc7ffa8b4091e425dfe6e857273a5bb90ad3b6c078f67e597c7623f7ec897d1d6d51df559efafabacea66269fc393c57bb62826104b1a6bdd943e3932db

test:
  secret_key_base: bf2c7be752eef8283f6979110d1b02ee3c56886c9c18aeec171142c31aef8b9da8afcc226737ada8add586b36513a581d202efa7a55e5b54c1ac13bc1716cdef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
